<?php

namespace Tests\Feature\Privacy;

use Tests\TestCase;

class ComplianceAssessmentTest extends TestCase
{
    private string $report = 'docs/reports/COMPLIANCE_ASSESSMENT_20261001.md';

    private function body(): string
    {
        return file_get_contents(base_path($this->report));
    }

    public function test_assessment_exists(): void
    {
        $this->assertFileExists(base_path($this->report));
    }

    public function test_assessment_lists_articles(): void
    {
        $body = $this->body();
        foreach (['Art. 7-8', 'Art. 13-14', 'Art. 18', 'Art. 26',
                  'Art. 27', 'Art. 28-31', 'Art. 30', 'Art. 33-40'] as $ref) {
            $this->assertStringContainsString($ref, $body, "Missing: $ref");
        }
    }

    public function test_assessment_lists_external_actions(): void
    {
        $body = $this->body();
        $this->assertStringContainsString('ECA registration', $body);
        $this->assertStringContainsString('DPO appointment', $body);
        $this->assertStringContainsString('Gemini DPA', $body);
    }

    public function test_assessment_has_sign_off(): void
    {
        $this->assertStringContainsString('Developer side', $this->body());
        $this->assertStringContainsString('Generated by:** L301', $this->body());
    }

    public function test_assessment_references_ledger_300(): void
    {
        $this->assertStringContainsString('e23696d', $this->body());
        $this->assertStringContainsString('L300', $this->body());
    }

    public function test_eca_letter_exists(): void
    {
        $this->assertFileExists(base_path('docs/privacy/ECA_REGISTRATION_LETTER.md'));
    }

    public function test_eca_letter_has_attachments(): void
    {
        $body = file_get_contents(base_path('docs/privacy/ECA_REGISTRATION_LETTER.md'));
        foreach (['Privacy Policy', 'Terms of Service', 'Data Retention Policy',
                  'DPIA Report', 'DPO Appointment', 'Breach Response Plan'] as $doc) {
            $this->assertStringContainsString($doc, $body, "Missing: $doc");
        }
    }

    public function test_dpo_announcement_exists(): void
    {
        $this->assertFileExists(base_path('docs/privacy/DPO_ANNOUNCEMENT.md'));
    }

    public function test_dpo_announcement_has_contact(): void
    {
        $body = file_get_contents(base_path('docs/privacy/DPO_ANNOUNCEMENT.md'));
        $this->assertStringContainsString('dpo@felagi.et', $body);
        $this->assertStringContainsString('Art. 27', $body);
    }
}
